#include <stdio.h>
#include <stdlib.h>

#include "hpipm/auxiliary/aux_mem.h"
#include "hpipm/auxiliary/aux_string.h"
#include "hpipm/ocp/d_ocp_qcqp_dim.h"
#include "hpipm/ocp/d_ocp_qp_dim.h"


#define OCP_QCQP_DIM d_ocp_qcqp_dim
#define OCP_QP_DIM d_ocp_qp_dim
#define OCP_QP_DIM_CREATE d_ocp_qp_dim_create
#define OCP_QP_DIM_MEMSIZE d_ocp_qp_dim_memsize
#define OCP_QP_DIM_SET_NX d_ocp_qp_dim_set_nx
#define OCP_QP_DIM_SET_NU d_ocp_qp_dim_set_nu
#define OCP_QP_DIM_SET_NBX d_ocp_qp_dim_set_nbx
#define OCP_QP_DIM_SET_NBU d_ocp_qp_dim_set_nbu
#define OCP_QP_DIM_SET_NG d_ocp_qp_dim_set_ng
#define OCP_QP_DIM_SET_NS d_ocp_qp_dim_set_ns
#define OCP_QP_DIM_SET_NSBX d_ocp_qp_dim_set_nsbx
#define OCP_QP_DIM_SET_NSBU d_ocp_qp_dim_set_nsbu
#define OCP_QP_DIM_SET_NSG d_ocp_qp_dim_set_nsg
#define OCP_QP_DIM_SET_NBXE d_ocp_qp_dim_set_nbxe
#define OCP_QP_DIM_SET_NBUE d_ocp_qp_dim_set_nbue
#define OCP_QP_DIM_SET_NGE d_ocp_qp_dim_set_nge


#define OCP_QCQP_DIM_STRSIZE d_ocp_qcqp_dim_strsize
#define OCP_QCQP_DIM_MEMSIZE d_ocp_qcqp_dim_memsize
#define OCP_QCQP_DIM_CREATE d_ocp_qcqp_dim_create
#define OCP_QCQP_DIM_COPY_ALL d_ocp_qcqp_dim_copy_all
#define OCP_QCQP_DIM_SET d_ocp_qcqp_dim_set
#define OCP_QCQP_DIM_SET_NX d_ocp_qcqp_dim_set_nx
#define OCP_QCQP_DIM_SET_NU d_ocp_qcqp_dim_set_nu
#define OCP_QCQP_DIM_SET_NBX d_ocp_qcqp_dim_set_nbx
#define OCP_QCQP_DIM_SET_NBU d_ocp_qcqp_dim_set_nbu
#define OCP_QCQP_DIM_SET_NG d_ocp_qcqp_dim_set_ng
#define OCP_QCQP_DIM_SET_NQ d_ocp_qcqp_dim_set_nq
#define OCP_QCQP_DIM_SET_NS d_ocp_qcqp_dim_set_ns
#define OCP_QCQP_DIM_SET_NSBX d_ocp_qcqp_dim_set_nsbx
#define OCP_QCQP_DIM_SET_NSBU d_ocp_qcqp_dim_set_nsbu
#define OCP_QCQP_DIM_SET_NSG d_ocp_qcqp_dim_set_nsg
#define OCP_QCQP_DIM_SET_NSQ d_ocp_qcqp_dim_set_nsq
#define OCP_QCQP_DIM_SET_NBXE d_ocp_qcqp_dim_set_nbxe
#define OCP_QCQP_DIM_SET_NBUE d_ocp_qcqp_dim_set_nbue
#define OCP_QCQP_DIM_SET_NGE d_ocp_qcqp_dim_set_nge
#define OCP_QCQP_DIM_SET_NQE d_ocp_qcqp_dim_set_nqe
#define OCP_QCQP_DIM_GET d_ocp_qcqp_dim_get
#define OCP_QCQP_DIM_GET_N d_ocp_qcqp_dim_get_N
#define OCP_QCQP_DIM_GET_NX d_ocp_qcqp_dim_get_nx
#define OCP_QCQP_DIM_GET_NU d_ocp_qcqp_dim_get_nu


#include "x_ocp_qcqp_dim.c"
