#include <stdio.h>
#include <stdlib.h>

#include "hpipm/auxiliary/aux_mem.h"
#include "hpipm/auxiliary/aux_string.h"
#include "hpipm/ocp/s_ocp_qcqp_dim.h"
#include "hpipm/ocp/s_ocp_qp_dim.h"


#define OCP_QCQP_DIM s_ocp_qcqp_dim
#define OCP_QP_DIM s_ocp_qp_dim
#define OCP_QP_DIM_CREATE s_ocp_qp_dim_create
#define OCP_QP_DIM_MEMSIZE s_ocp_qp_dim_memsize
#define OCP_QP_DIM_SET_NX s_ocp_qp_dim_set_nx
#define OCP_QP_DIM_SET_NU s_ocp_qp_dim_set_nu
#define OCP_QP_DIM_SET_NBX s_ocp_qp_dim_set_nbx
#define OCP_QP_DIM_SET_NBU s_ocp_qp_dim_set_nbu
#define OCP_QP_DIM_SET_NG s_ocp_qp_dim_set_ng
#define OCP_QP_DIM_SET_NS s_ocp_qp_dim_set_ns
#define OCP_QP_DIM_SET_NSBX s_ocp_qp_dim_set_nsbx
#define OCP_QP_DIM_SET_NSBU s_ocp_qp_dim_set_nsbu
#define OCP_QP_DIM_SET_NSG s_ocp_qp_dim_set_nsg
#define OCP_QP_DIM_SET_NBXE s_ocp_qp_dim_set_nbxe
#define OCP_QP_DIM_SET_NBUE s_ocp_qp_dim_set_nbue
#define OCP_QP_DIM_SET_NGE s_ocp_qp_dim_set_nge


#define OCP_QCQP_DIM_STRSIZE s_ocp_qcqp_dim_strsize
#define OCP_QCQP_DIM_MEMSIZE s_ocp_qcqp_dim_memsize
#define OCP_QCQP_DIM_CREATE s_ocp_qcqp_dim_create
#define OCP_QCQP_DIM_COPY_ALL s_ocp_qcqp_dim_copy_all
#define OCP_QCQP_DIM_SET s_ocp_qcqp_dim_set
#define OCP_QCQP_DIM_SET_NX s_ocp_qcqp_dim_set_nx
#define OCP_QCQP_DIM_SET_NU s_ocp_qcqp_dim_set_nu
#define OCP_QCQP_DIM_SET_NBX s_ocp_qcqp_dim_set_nbx
#define OCP_QCQP_DIM_SET_NBU s_ocp_qcqp_dim_set_nbu
#define OCP_QCQP_DIM_SET_NG s_ocp_qcqp_dim_set_ng
#define OCP_QCQP_DIM_SET_NQ s_ocp_qcqp_dim_set_nq
#define OCP_QCQP_DIM_SET_NS s_ocp_qcqp_dim_set_ns
#define OCP_QCQP_DIM_SET_NSBX s_ocp_qcqp_dim_set_nsbx
#define OCP_QCQP_DIM_SET_NSBU s_ocp_qcqp_dim_set_nsbu
#define OCP_QCQP_DIM_SET_NSG s_ocp_qcqp_dim_set_nsg
#define OCP_QCQP_DIM_SET_NSQ s_ocp_qcqp_dim_set_nsq
#define OCP_QCQP_DIM_SET_NBXE s_ocp_qcqp_dim_set_nbxe
#define OCP_QCQP_DIM_SET_NBUE s_ocp_qcqp_dim_set_nbue
#define OCP_QCQP_DIM_SET_NGE s_ocp_qcqp_dim_set_nge
#define OCP_QCQP_DIM_SET_NQE s_ocp_qcqp_dim_set_nqe
#define OCP_QCQP_DIM_GET s_ocp_qcqp_dim_get
#define OCP_QCQP_DIM_GET_N s_ocp_qcqp_dim_get_N
#define OCP_QCQP_DIM_GET_NX s_ocp_qcqp_dim_get_nx
#define OCP_QCQP_DIM_GET_NU s_ocp_qcqp_dim_get_nu


#include "x_ocp_qcqp_dim.c"
